[tool.ruff]
target-version = "py310"
line-length = 100

[tool.ruff.lint]
select = [
  "E",  # pycodestyle errors
  "F",  # pyflakes
]
ignore = []


[tool.black]
line-length = 100
target-version = ["py310"]
