name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  python:
    uses: matheussiqueirahub/banco_aurora/.github/workflows/python-ci.yml@main
    with:
      matrix-os: '["ubuntu-latest", "windows-latest"]'
      python-versions: '["3.10", "3.11"]'
      run-lint: true
      run-tests: true
      coverage: true
      validate-script: true
      script-path-glob: 'Program*Orientada-a-Objetos.py'
      script-expected: |
        Veículo está em movimento.
        Carro está dirigindo.
        Moto está acelerando.
        Saldo atual de Ana: R$ 120.00
